import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        About
      </h1>

      <p>This page was reached by accessing / and the middleware.ts edge function redirecting to /about</p>
    </div>
  )
}

export default About
